# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Best Sellers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Best Sellers
  pod 'Alamofire'

  target 'Best SellersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Best SellersUITests' do
    # Pods for testing
  end

end
